server.port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG
  org.flywaydb.core: DEBUG

s3:
  endpointUrl: http://localhost:9000
  accessKey: Q68GV9SY1H2SOSQAZ2NT
  secretKey: Gfl5B7bu87F5KVzd/NR1PXmRKbiHZ6UaYlra6mDK
  bucketName: moviefun
