spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl: http://localhost:9000
  accessKey: Q68GV9SY1H2SOSQAZ2NT
  secretKey: Gfl5B7bu87F5KVzd/NR1PXmRKbiHZ6UaYlra6mDK
  bucketName: moviefun

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
