spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

  application:
    name: movie-fun-app

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

security:
  basic:
    enabled: false

movies:
  url: //movie-service/movies
albums:
  url: //album-service/albums